/* Generated By:JavaCC: Do not edit this line. SintacticoMasterConstants.java */
package com.jagt.Analizadores.XML.Master;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SintacticoMasterConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CADENA = 7;
  /** RegularExpression Id. */
  int INICIO_BD = 8;
  /** RegularExpression Id. */
  int FIN_BD = 9;
  /** RegularExpression Id. */
  int INICIO_NOMBRE = 10;
  /** RegularExpression Id. */
  int FIN_NOMBRE = 11;
  /** RegularExpression Id. */
  int INICIO_RUTA = 12;
  /** RegularExpression Id. */
  int FIN_RUTA = 13;
  /** RegularExpression Id. */
  int INICIO_PERMISOS = 14;
  /** RegularExpression Id. */
  int FIN_PERMISOS = 15;
  /** RegularExpression Id. */
  int INICIO_USUARIO = 16;
  /** RegularExpression Id. */
  int FIN_USUARIO = 17;
  /** RegularExpression Id. */
  int ID = 18;
  /** RegularExpression Id. */
  int NUMERO = 19;
  /** RegularExpression Id. */
  int DIGITO = 20;
  /** RegularExpression Id. */
  int LETRA = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\b\"",
    "<CADENA>",
    "\"<DB>\"",
    "\"</DB>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<path>\"",
    "\"</path>\"",
    "\"<permisos>\"",
    "\"</permisos>\"",
    "\"<usuario>\"",
    "\"</usuario>\"",
    "<ID>",
    "<NUMERO>",
    "<DIGITO>",
    "<LETRA>",
  };

}
