/* Generated By:JavaCC: Do not edit this line. SintacticoConstants.java */
package com.jagt.Analizadores.USQL;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SintacticoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINEA = 7;
  /** RegularExpression Id. */
  int MULTILINEA = 8;
  /** RegularExpression Id. */
  int ENTERO = 9;
  /** RegularExpression Id. */
  int DOBLE = 10;
  /** RegularExpression Id. */
  int CADENA = 11;
  /** RegularExpression Id. */
  int FECHA = 12;
  /** RegularExpression Id. */
  int HORA = 13;
  /** RegularExpression Id. */
  int RES_DOBLE = 14;
  /** RegularExpression Id. */
  int RES_ENTERO = 15;
  /** RegularExpression Id. */
  int RES_CADENA = 16;
  /** RegularExpression Id. */
  int RES_BOOLEAN = 17;
  /** RegularExpression Id. */
  int RES_DATE = 18;
  /** RegularExpression Id. */
  int RES_DATETIME = 19;
  /** RegularExpression Id. */
  int VERDADERO = 20;
  /** RegularExpression Id. */
  int FALSO = 21;
  /** RegularExpression Id. */
  int RES_CREAR = 22;
  /** RegularExpression Id. */
  int RES_BD = 23;
  /** RegularExpression Id. */
  int RES_TABLA = 24;
  /** RegularExpression Id. */
  int RES_OBJETO = 25;
  /** RegularExpression Id. */
  int RES_PROCEDIMIENTO = 26;
  /** RegularExpression Id. */
  int RES_FUNCION = 27;
  /** RegularExpression Id. */
  int RETORNAR = 28;
  /** RegularExpression Id. */
  int RES_USUARIO = 29;
  /** RegularExpression Id. */
  int RES_PASSWORD = 30;
  /** RegularExpression Id. */
  int RES_COLOCAR = 31;
  /** RegularExpression Id. */
  int RES_USAR = 32;
  /** RegularExpression Id. */
  int RES_ALTERAR = 33;
  /** RegularExpression Id. */
  int RES_AGREGAR = 34;
  /** RegularExpression Id. */
  int RES_QUITAR = 35;
  /** RegularExpression Id. */
  int RES_CAMBIAR = 36;
  /** RegularExpression Id. */
  int RES_ELIMINAR = 37;
  /** RegularExpression Id. */
  int RES_INSERTAR = 38;
  /** RegularExpression Id. */
  int RES_EN = 39;
  /** RegularExpression Id. */
  int RES_VALORES = 40;
  /** RegularExpression Id. */
  int RES_DONDE = 41;
  /** RegularExpression Id. */
  int RES_ACTUALIZAR = 42;
  /** RegularExpression Id. */
  int RES_BORRAR = 43;
  /** RegularExpression Id. */
  int RES_SELECCIONAR = 44;
  /** RegularExpression Id. */
  int RES_DE = 45;
  /** RegularExpression Id. */
  int RES_OTORGAR = 46;
  /** RegularExpression Id. */
  int RES_DENEGAR = 47;
  /** RegularExpression Id. */
  int RES_PERMISOS = 48;
  /** RegularExpression Id. */
  int RES_ORDENAR = 49;
  /** RegularExpression Id. */
  int RES_ASC = 50;
  /** RegularExpression Id. */
  int RES_DESC = 51;
  /** RegularExpression Id. */
  int RES_DECLARAR = 52;
  /** RegularExpression Id. */
  int RES_IMPRIMIR = 53;
  /** RegularExpression Id. */
  int RES_FECHA = 54;
  /** RegularExpression Id. */
  int RES_FECHAHORA = 55;
  /** RegularExpression Id. */
  int RES_CONTAR = 56;
  /** RegularExpression Id. */
  int RES_BACKUP = 57;
  /** RegularExpression Id. */
  int RES_USQLDUMP = 58;
  /** RegularExpression Id. */
  int RES_COMPLETO = 59;
  /** RegularExpression Id. */
  int RES_RESTAURAR = 60;
  /** RegularExpression Id. */
  int SI = 61;
  /** RegularExpression Id. */
  int SINO = 62;
  /** RegularExpression Id. */
  int SELECCIONA = 63;
  /** RegularExpression Id. */
  int CASO = 64;
  /** RegularExpression Id. */
  int DEFECTO = 65;
  /** RegularExpression Id. */
  int DETENER = 66;
  /** RegularExpression Id. */
  int PARA = 67;
  /** RegularExpression Id. */
  int MIENTRAS = 68;
  /** RegularExpression Id. */
  int INCREMENTO = 69;
  /** RegularExpression Id. */
  int DECREMENTO = 70;
  /** RegularExpression Id. */
  int PUNTO = 71;
  /** RegularExpression Id. */
  int MAS = 72;
  /** RegularExpression Id. */
  int MENOS = 73;
  /** RegularExpression Id. */
  int POR = 74;
  /** RegularExpression Id. */
  int DIV = 75;
  /** RegularExpression Id. */
  int POT = 76;
  /** RegularExpression Id. */
  int MAYOR = 77;
  /** RegularExpression Id. */
  int MENOR = 78;
  /** RegularExpression Id. */
  int IGUAL = 79;
  /** RegularExpression Id. */
  int DIFERENTE = 80;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 81;
  /** RegularExpression Id. */
  int MAYOR_IGUAL = 82;
  /** RegularExpression Id. */
  int ASIGNA = 83;
  /** RegularExpression Id. */
  int RES_NO = 84;
  /** RegularExpression Id. */
  int RES_NULO = 85;
  /** RegularExpression Id. */
  int RES_AUTOINC = 86;
  /** RegularExpression Id. */
  int RES_PRIMARIA = 87;
  /** RegularExpression Id. */
  int RES_FORANEA = 88;
  /** RegularExpression Id. */
  int RES_UNICO = 89;
  /** RegularExpression Id. */
  int OR = 90;
  /** RegularExpression Id. */
  int AND = 91;
  /** RegularExpression Id. */
  int NOT = 92;
  /** RegularExpression Id. */
  int ID = 93;
  /** RegularExpression Id. */
  int VAR = 94;
  /** RegularExpression Id. */
  int DIGITO = 95;
  /** RegularExpression Id. */
  int LETRA = 96;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\b\"",
    "<LINEA>",
    "<MULTILINEA>",
    "<ENTERO>",
    "<DOBLE>",
    "<CADENA>",
    "<FECHA>",
    "<HORA>",
    "\"Double\"",
    "\"Integer\"",
    "\"Text\"",
    "\"Bool\"",
    "\"Date\"",
    "\"Datetime\"",
    "<VERDADERO>",
    "<FALSO>",
    "\"Crear\"",
    "\"Base_Datos\"",
    "\"Tabla\"",
    "\"Objeto\"",
    "\"Procedimiento\"",
    "\"Funcion\"",
    "\"Retorno\"",
    "\"Usuario\"",
    "\"Password\"",
    "\"Colocar\"",
    "\"Usar\"",
    "\"Alterar\"",
    "\"Agregar\"",
    "\"Quitar\"",
    "\"Cambiar\"",
    "\"Eliminar\"",
    "\"Insertar\"",
    "\"En\"",
    "\"Valores\"",
    "\"Donde\"",
    "\"Actualizar\"",
    "\"Borrar\"",
    "\"Seleccionar\"",
    "\"De\"",
    "\"Otorgar\"",
    "\"Denegar\"",
    "\"Permisos\"",
    "\"Ordenar_Por\"",
    "\"ASC\"",
    "\"DESC\"",
    "\"Declarar\"",
    "\"Imprimir\"",
    "\"Fecha\"",
    "\"Fecha_Hora\"",
    "\"Contar\"",
    "\"Backup\"",
    "\"USQLDUMP\"",
    "\"Completo\"",
    "\"Restaurar\"",
    "\"Si\"",
    "\"Sino\"",
    "\"Selecciona\"",
    "\"Caso\"",
    "\"Defecto\"",
    "\"Detener\"",
    "\"Para\"",
    "\"Mientras\"",
    "\"++\"",
    "\"--\"",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"No\"",
    "\"Nulo\"",
    "\"Autoincrementable\"",
    "\"Llave_Primaria\"",
    "\"Llave_Foranea\"",
    "\"Unico\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "<ID>",
    "<VAR>",
    "<DIGITO>",
    "<LETRA>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
  };

}
