/* Generated By:JavaCC: Do not edit this line. Sintactico.java */
package com.jagt.Analizadores.USQL;
import com.jagt.AST.*;
public class Sintactico implements SintacticoConstants {

        public static void main(String args[]) throws ParseException{

                Sintactico parser = new Sintactico(System.in);
                parser.inicio();

        }

  final public int inicio() throws ParseException {
 NodoParser cuerpos,c;
         cuerpos = new NodoParser("CUERPOS","",1,1);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case RES_CREAR:
      case RETORNAR:
      case RES_USAR:
      case RES_ALTERAR:
      case RES_ELIMINAR:
      case RES_INSERTAR:
      case RES_ACTUALIZAR:
      case RES_BORRAR:
      case RES_SELECCIONAR:
      case RES_OTORGAR:
      case RES_DENEGAR:
      case RES_DECLARAR:
      case RES_IMPRIMIR:
      case RES_CONTAR:
      case RES_BACKUP:
      case RES_RESTAURAR:
      case SI:
      case SELECCIONA:
      case DETENER:
      case PARA:
      case MIENTRAS:
      case ID:
      case VAR:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      c = instruccionSQL();
                                       cuerpos.hijos().add(c);
    }
    jj_consume_token(0);
         AST arbol = new AST(); arbol.graficar(cuerpos); Compilador compi = new Compilador(cuerpos); {if (true) return 0;}
    throw new Error("Missing return statement in function");
  }

  final public void Empty() throws ParseException {
     System.out.println("epsilon");
  }

  final public NodoParser instruccionSQL() throws ParseException {
 NodoParser ins;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RES_CREAR:
      ins = crear();
                                 {if (true) return ins;}
      break;
    case RES_USAR:
      ins = usar();
                                 {if (true) return ins;}
      break;
    case RES_ALTERAR:
      ins = alterar();
                                 {if (true) return ins;}
      break;
    case RETORNAR:
    case RES_ELIMINAR:
    case RES_INSERTAR:
    case RES_ACTUALIZAR:
    case RES_BORRAR:
    case RES_SELECCIONAR:
    case RES_DECLARAR:
    case RES_IMPRIMIR:
    case RES_CONTAR:
    case SI:
    case SELECCIONA:
    case DETENER:
    case PARA:
    case MIENTRAS:
    case ID:
    case VAR:
      ins = sentencia();
                                 {if (true) return ins;}
      break;
    case RES_OTORGAR:
      ins = otorgar();
                                 {if (true) return ins;}
      break;
    case RES_DENEGAR:
      ins = denegar();
                                 {if (true) return ins;}
      break;
    case RES_BACKUP:
      ins = backup();
                                 {if (true) return ins;}
      break;
    case RES_RESTAURAR:
      ins = restaurar();
                                 {if (true) return ins;}
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser sentencia() throws ParseException {
 NodoParser sen;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RES_INSERTAR:
      sen = insertar();
                                 {if (true) return sen;}
      break;
    case RES_ELIMINAR:
      sen = eliminar();
                                 {if (true) return sen;}
      break;
    case RES_SELECCIONAR:
      sen = seleccionar();
      jj_consume_token(99);
                                 {if (true) return sen;}
      break;
    case RES_ACTUALIZAR:
      sen = actualizar();
                                 {if (true) return sen;}
      break;
    case RES_BORRAR:
      sen = borrar();
                                 {if (true) return sen;}
      break;
    case RES_DECLARAR:
      sen = declarar();
                                 {if (true) return sen;}
      break;
    case VAR:
      sen = asignar();
                                 {if (true) return sen;}
      break;
    case RES_IMPRIMIR:
      sen = imprimir();
                                 {if (true) return sen;}
      break;
    case ID:
      sen = llamada();
                                 {if (true) return sen;}
      jj_consume_token(99);
      break;
    case RETORNAR:
      sen = retorno();
                                 {if (true) return sen;}
      break;
    case DETENER:
      sen = detener();
                                 {if (true) return sen;}
      break;
    case SI:
    case SELECCIONA:
    case PARA:
    case MIENTRAS:
      sen = control();
                                 {if (true) return sen;}
      break;
    case RES_CONTAR:
      sen = contar();
      jj_consume_token(99);
                                 {if (true) return sen;}
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser contar() throws ParseException {
 NodoParser nodo,sel; Token t;
    t = jj_consume_token(RES_CONTAR);
                         nodo = new NodoParser("CONTAR","",t.beginLine,t.beginColumn);
    jj_consume_token(100);
    jj_consume_token(MENOR);
    jj_consume_token(MENOR);
    sel = seleccionar();
                         nodo.hijos().add(sel);
    jj_consume_token(MAYOR);
    jj_consume_token(MAYOR);
    jj_consume_token(101);
     {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser lista_sentencias() throws ParseException {
 NodoParser sentencias,s;
         sentencias = new NodoParser("SENTENCIAS","",0,0);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case RETORNAR:
      case RES_ELIMINAR:
      case RES_INSERTAR:
      case RES_ACTUALIZAR:
      case RES_BORRAR:
      case RES_SELECCIONAR:
      case RES_DECLARAR:
      case RES_IMPRIMIR:
      case RES_CONTAR:
      case SI:
      case SELECCIONA:
      case DETENER:
      case PARA:
      case MIENTRAS:
      case ID:
      case VAR:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      s = sentencia();
                             sentencias.hijos().add(s);
    }
         {if (true) return sentencias;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser detener() throws ParseException {
 Token t; NodoParser nodo;
    t = jj_consume_token(DETENER);
                       nodo = new NodoParser("DETENER","",t.beginLine,t.beginColumn);
    jj_consume_token(99);
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser retorno() throws ParseException {
 Token t; NodoParser nodo,exp;
    t = jj_consume_token(RETORNAR);
                             nodo = new NodoParser("RETORNAR","",t.beginLine,t.beginColumn);
    exp = expresion();
                             nodo.hijos().add(exp);
    jj_consume_token(99);
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser restaurar() throws ParseException {
 NodoParser nodo,tipo; Token t,cad;
    t = jj_consume_token(RES_RESTAURAR);
                                 nodo = new NodoParser("RESTAURAR","",t.beginLine,t.beginColumn);
    tipo = tipo_backup();
                                 nodo.hijos().add(tipo);
    cad = jj_consume_token(CADENA);
                                 nodo.hijos().add(new NodoParser("CADENA",cad.image,cad.beginLine,cad.beginColumn));
    jj_consume_token(99);
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser backup() throws ParseException {
 NodoParser nodo,tipo; Token t,id1,id2;
    t = jj_consume_token(RES_BACKUP);
                                 nodo = new NodoParser("BACKUP","",t.beginLine,t.beginColumn);
    tipo = tipo_backup();
                                 nodo.hijos().add(tipo);
    id1 = jj_consume_token(ID);
                                 nodo.hijos().add(new NodoParser("ID",id1.image,id1.beginLine,id1.beginColumn));
    id2 = jj_consume_token(ID);
                                 nodo.hijos().add(new NodoParser("ID",id2.image,id2.beginLine,id2.beginColumn));
    jj_consume_token(99);
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser tipo_backup() throws ParseException {
 Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RES_USQLDUMP:
      t = jj_consume_token(RES_USQLDUMP);
                                 {if (true) return new NodoParser("TIPO","USQLDUMP",t.beginLine,t.beginColumn);}
      break;
    case RES_COMPLETO:
      t = jj_consume_token(RES_COMPLETO);
                                 {if (true) return new NodoParser("TIPO","COMPLETO",t.beginLine,t.beginColumn);}
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser imprimir() throws ParseException {
 NodoParser nodo,exp; Token t;
    t = jj_consume_token(RES_IMPRIMIR);
                                 nodo = new NodoParser("IMPRIMIR","",t.beginLine,t.beginColumn);
    jj_consume_token(100);
    exp = expresion();
                                 nodo.hijos().add(exp);
    jj_consume_token(101);
    jj_consume_token(99);
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser asignar() throws ParseException {
 Token v,id; NodoParser nodo = new NodoParser("ASIGNAR","",0,0); NodoParser acceso,exp;
    v = jj_consume_token(VAR);
                                 nodo.hijos().add(new NodoParser("VAR",v.image,v.beginLine,v.beginColumn));
         acceso = new NodoParser("ACCESO","",0,0);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PUNTO:
      jj_consume_token(PUNTO);
      id = jj_consume_token(ID);
                                 acceso.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
         nodo.hijos().add(acceso);
    jj_consume_token(ASIGNA);
    exp = expresion();
                                 nodo.hijos().add(exp);
    jj_consume_token(99);
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser declarar() throws ParseException {
 NodoParser declara = new NodoParser("DECLARAR","",0,0); NodoParser vars,tipov,exp;
    jj_consume_token(RES_DECLARAR);
    vars = lista_variables();
                                     declara.hijos().add(vars);
    tipov = tipo();
                                     declara.hijos().add(tipov);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASIGNA:
      jj_consume_token(ASIGNA);
      exp = expresion();
                                     declara.hijos().add(exp);
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    jj_consume_token(99);
         {if (true) return declara;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser lista_variables() throws ParseException {
 NodoParser nodo = new NodoParser("VARIABLES","",0,0); NodoParser var; Token v;
    v = jj_consume_token(VAR);
                         nodo.hijos().add(new NodoParser("VAR",v.image,v.beginLine,v.beginColumn));
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 102:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_3;
      }
      jj_consume_token(102);
      v = jj_consume_token(VAR);
                         nodo.hijos().add(new NodoParser("VAR",v.image,v.beginLine,v.beginColumn));
    }
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser denegar() throws ParseException {
 NodoParser nodo,tipo; Token t,id;
    t = jj_consume_token(RES_DENEGAR);
                                 nodo = new NodoParser("DENEGAR","",t.beginLine,t.beginColumn);
    jj_consume_token(RES_PERMISOS);
    id = jj_consume_token(ID);
                                 nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
    jj_consume_token(102);
    id = jj_consume_token(ID);
                                 nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
    jj_consume_token(PUNTO);
    tipo = tipo_permiso();
                                 nodo.hijos().add(tipo);
    jj_consume_token(99);
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser otorgar() throws ParseException {
 NodoParser nodo,tipo; Token t,id;
    t = jj_consume_token(RES_OTORGAR);
                                 nodo = new NodoParser("OTORGAR","",t.beginLine,t.beginColumn);
    jj_consume_token(RES_PERMISOS);
    id = jj_consume_token(ID);
                                 nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
    jj_consume_token(102);
    id = jj_consume_token(ID);
                                 nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
    jj_consume_token(PUNTO);
    tipo = tipo_permiso();
                                 nodo.hijos().add(tipo);
    jj_consume_token(99);
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser tipo_permiso() throws ParseException {
 NodoParser tipo; Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ID:
      t = jj_consume_token(ID);
                                 {if (true) return new NodoParser("TIPO",t.image,t.beginLine,t.beginColumn);}
      break;
    case POR:
      t = jj_consume_token(POR);
                                 {if (true) return new NodoParser("TIPO","*",t.beginLine,t.beginColumn);}
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser borrar() throws ParseException {
 NodoParser nodo,d; Token t,id;
    t = jj_consume_token(RES_BORRAR);
                                 nodo = new NodoParser("BORRAR",t.image,t.beginLine,t.beginColumn);
    jj_consume_token(RES_EN);
    jj_consume_token(RES_TABLA);
    id = jj_consume_token(ID);
                                 nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RES_DONDE:
      d = donde();
                                 nodo.hijos().add(d);
      break;
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    jj_consume_token(99);
                                 {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser actualizar() throws ParseException {
 NodoParser nodo,lista,d,exps; Token t,id;
    t = jj_consume_token(RES_ACTUALIZAR);
                                     nodo = new NodoParser("ACTUALIZAR",t.image,t.beginLine,t.beginColumn);
    jj_consume_token(RES_TABLA);
    id = jj_consume_token(ID);
                                     nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
    jj_consume_token(100);
    lista = lista_ids();
                                     nodo.hijos().add(lista);
    jj_consume_token(101);
    jj_consume_token(RES_VALORES);
    jj_consume_token(100);
    exps = lista_expresiones();
                                     nodo.hijos().add(exps);
    jj_consume_token(101);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RES_DONDE:
      d = donde();
                                     nodo.hijos().add(d);
      break;
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    jj_consume_token(99);
                                     {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser seleccionar() throws ParseException {
 NodoParser nodo,s,d,tipo,o,lista,id; Token or,t;
    t = jj_consume_token(RES_SELECCIONAR);
                                     nodo = new NodoParser("SELECCIONAR",t.image,t.beginLine,t.beginColumn);
    s = seleccion();
                                     nodo.hijos().add(s);
    jj_consume_token(RES_DE);
    lista = lista_ids();
                                  nodo.hijos().add(lista);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RES_DONDE:
      d = donde();
                                     nodo.hijos().add(d);
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RES_ORDENAR:
      or = jj_consume_token(RES_ORDENAR);
                                     o = new NodoParser("ORDENAR",or.image,or.beginLine,or.beginColumn);
      id = acceso();
                                     o.hijos().add(id);
      tipo = tipo_orden();
                                     o.hijos().add(tipo); nodo.hijos().add(o);
      break;
    default:
      jj_la1[12] = jj_gen;
      ;
    }
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser lista_acceso() throws ParseException {
 NodoParser sentencias,s;
         sentencias = new NodoParser("LISTA_ACCESO","",0,0);
    s = acceso();
                      sentencias.hijos().add(s);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 102:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_4;
      }
      jj_consume_token(102);
      s = acceso();
                          sentencias.hijos().add(s);
    }
         {if (true) return sentencias;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser acceso() throws ParseException {
 NodoParser nodo = new NodoParser("ACCESO","",0,0); NodoParser a; Token t;
    a = tipo_acceso();
                              nodo.hijos().add(a);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUNTO:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_5;
      }
      jj_consume_token(PUNTO);
      t = jj_consume_token(ID);
                              nodo.hijos().add(new NodoParser("ID",t.image,t.beginLine,t.beginColumn));
    }
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser tipo_acceso() throws ParseException {
 Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VAR:
      t = jj_consume_token(VAR);
                     {if (true) return new NodoParser("VAR",t.image,t.beginLine,t.beginColumn);}
      break;
    case ID:
      t = jj_consume_token(ID);
                     {if (true) return new NodoParser("ID",t.image,t.beginLine,t.beginColumn);}
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser seleccion() throws ParseException {
 NodoParser nodo; Token id;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ID:
    case VAR:
      nodo = lista_acceso();
                                     {if (true) return nodo;}
      break;
    case POR:
      id = jj_consume_token(POR);
                                     {if (true) return new NodoParser("TODO",id.image,id.beginLine,id.beginColumn);}
      break;
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser tipo_orden() throws ParseException {
 NodoParser nodo; Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RES_ASC:
      t = jj_consume_token(RES_ASC);
                                     {if (true) return new NodoParser("ASC",t.image,t.beginLine,t.beginColumn);}
      break;
    case RES_DESC:
      t = jj_consume_token(RES_DESC);
                                     {if (true) return new NodoParser("DESC",t.image,t.beginLine,t.beginColumn);}
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser donde() throws ParseException {
 NodoParser cond;
    jj_consume_token(RES_DONDE);
    cond = condicion();
                                     {if (true) return cond;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser eliminar() throws ParseException {
 NodoParser nodo,tipo; Token t;
    t = jj_consume_token(RES_ELIMINAR);
                                     nodo = new NodoParser("ELIMINAR",t.image,t.beginLine,t.beginColumn);
    tipo = tipo_eliminar();
                                     nodo.hijos().add(tipo);
    jj_consume_token(99);
                                     {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser tipo_eliminar() throws ParseException {
 NodoParser tipo; Token t,id;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RES_TABLA:
      t = jj_consume_token(RES_TABLA);
                                     tipo = new NodoParser("TIPO",t.image,t.beginLine,t.beginColumn);
      id = jj_consume_token(ID);
                                     tipo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn)); {if (true) return tipo;}
      break;
    case RES_OBJETO:
      t = jj_consume_token(RES_OBJETO);
                                     tipo = new NodoParser("TIPO",t.image,t.beginLine,t.beginColumn);
      id = jj_consume_token(ID);
                                     tipo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn)); {if (true) return tipo;}
      break;
    case RES_BD:
      t = jj_consume_token(RES_BD);
                                     tipo = new NodoParser("TIPO",t.image,t.beginLine,t.beginColumn);
      id = jj_consume_token(ID);
                                     tipo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn)); {if (true) return tipo;}
      break;
    case RES_USUARIO:
      t = jj_consume_token(RES_USUARIO);
                                     tipo = new NodoParser("TIPO",t.image,t.beginLine,t.beginColumn);
      id = jj_consume_token(ID);
                                     tipo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn)); {if (true) return tipo;}
      break;
    case RES_PROCEDIMIENTO:
      t = jj_consume_token(RES_PROCEDIMIENTO);
                                     tipo = new NodoParser("TIPO",t.image,t.beginLine,t.beginColumn);
      id = jj_consume_token(ID);
                                     tipo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn)); {if (true) return tipo;}
      break;
    case RES_FUNCION:
      t = jj_consume_token(RES_FUNCION);
                                     tipo = new NodoParser("TIPO",t.image,t.beginLine,t.beginColumn);
      id = jj_consume_token(ID);
                                     tipo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn)); {if (true) return tipo;}
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser llamada() throws ParseException {
 NodoParser nodo,temp,lista; Token id;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ID:
      id = jj_consume_token(ID);
                                         nodo = new NodoParser("ACCESO","",0,0); nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUNTO:
      case 100:
        temp = tipo_llamada();
                                            nodo = temp;
                                            nodo.hijos().addFirst(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
        break;
      default:
        jj_la1[19] = jj_gen;
        ;
      }
         {if (true) return nodo;}
      break;
    case VAR:
      id = jj_consume_token(VAR);
                                         nodo = new NodoParser("ACCESO","",0,0); nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUNTO:
        jj_consume_token(PUNTO);
        id = jj_consume_token(ID);
                                         nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
        break;
      default:
        jj_la1[20] = jj_gen;
        ;
      }
         {if (true) return nodo;}
      break;
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser tipo_llamada() throws ParseException {
 NodoParser nodo = new NodoParser("ACCESO","",0,0); NodoParser lista; Token id;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 100:
      jj_consume_token(100);
      lista = lista_expresiones();
                                     nodo = new NodoParser("LLAMADA","",0,0); nodo.hijos().add(lista);
      jj_consume_token(101);
         {if (true) return nodo;}
      break;
    case PUNTO:
      jj_consume_token(PUNTO);
      id = jj_consume_token(ID);
                                         nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUNTO:
        jj_consume_token(PUNTO);
        id = jj_consume_token(ID);
                                         nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
        break;
      default:
        jj_la1[22] = jj_gen;
        ;
      }
         {if (true) return nodo;}
      break;
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser insertar() throws ParseException {
 NodoParser nodo,lista,exps; Token t,id;
    t = jj_consume_token(RES_INSERTAR);
                                     nodo = new NodoParser("INSERTAR",t.image,t.beginLine,t.beginColumn);
    jj_consume_token(RES_EN);
    jj_consume_token(RES_TABLA);
    id = jj_consume_token(ID);
                                     nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 100:
      jj_consume_token(100);
      lista = lista_ids();
                                     nodo.hijos().add(lista);
      jj_consume_token(101);
      break;
    default:
      jj_la1[24] = jj_gen;
      ;
    }
    jj_consume_token(RES_VALORES);
    jj_consume_token(100);
    exps = lista_expresiones();
                                     nodo.hijos().add(exps);
    jj_consume_token(101);
    jj_consume_token(99);
                                     {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser alterar() throws ParseException {
 NodoParser nodo,tipo; Token t;
    t = jj_consume_token(RES_ALTERAR);
                                      nodo = new NodoParser("ALTERAR",t.image,t.beginLine,t.beginColumn);
    tipo = tipo_alterar();
                                      nodo.hijos().add(tipo);
    jj_consume_token(99);
                                      {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser tipo_alterar() throws ParseException {
 NodoParser nodo,tipo; Token t,id,cad;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RES_OBJETO:
      t = jj_consume_token(RES_OBJETO);
                                     nodo = new NodoParser("TIPO",t.image,t.beginLine,t.beginColumn);
      id = jj_consume_token(ID);
                                     nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
      tipo = tipo_opalterar();
                                     nodo.hijos().add(tipo); {if (true) return nodo;}
      break;
    case RES_TABLA:
      t = jj_consume_token(RES_TABLA);
                                     nodo = new NodoParser("TIPO",t.image,t.beginLine,t.beginColumn);
      id = jj_consume_token(ID);
                                     nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
      tipo = tipo_opalterar();
                                     nodo.hijos().add(tipo);
      break;
    case RES_USUARIO:
      t = jj_consume_token(RES_USUARIO);
                                     nodo = new NodoParser("TIPO",t.image,t.beginLine,t.beginColumn);
      id = jj_consume_token(ID);
                                     nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
      jj_consume_token(RES_CAMBIAR);
      jj_consume_token(RES_PASSWORD);
      jj_consume_token(ASIGNA);
      cad = jj_consume_token(CADENA);
                                     nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
      break;
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser tipo_opalterar() throws ParseException {
 NodoParser nodo,lista; Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RES_AGREGAR:
      t = jj_consume_token(RES_AGREGAR);
                                     nodo = new NodoParser("AGREGAR",t.image,t.beginLine,t.beginColumn);
      jj_consume_token(100);
      lista = lista_campos();
                                     nodo.hijos().add(lista); {if (true) return nodo;}
      jj_consume_token(101);
      break;
    case RES_QUITAR:
      t = jj_consume_token(RES_QUITAR);
                                     nodo = new NodoParser("QUITAR",t.image,t.beginLine,t.beginColumn);
      lista = lista_ids();
                                     nodo.hijos().add(lista); {if (true) return nodo;}
      break;
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser lista_ids() throws ParseException {
 NodoParser nodo; Token id;
    id = jj_consume_token(ID);
                                     nodo = new NodoParser("IDS","",0,0); nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 102:
        ;
        break;
      default:
        jj_la1[27] = jj_gen;
        break label_6;
      }
      jj_consume_token(102);
      id = jj_consume_token(ID);
                                     nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
    }
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser usar() throws ParseException {
 NodoParser nodo; Token t,id;
    t = jj_consume_token(RES_USAR);
                                     nodo = new NodoParser("USAR",t.image,t.beginLine,t.beginColumn);
    id = jj_consume_token(ID);
                                     nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
    jj_consume_token(99);
                                     {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser crear() throws ParseException {
 NodoParser tipo;
    jj_consume_token(RES_CREAR);
    tipo = tipo_crear();
                                     {if (true) return tipo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser tipo_crear() throws ParseException {
 NodoParser nodo;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RES_BD:
      nodo = crear_base();
                                     {if (true) return nodo;}
      break;
    case RES_TABLA:
      nodo = crear_tabla();
                                     {if (true) return nodo;}
      break;
    case RES_OBJETO:
      nodo = crear_objeto();
                                     {if (true) return nodo;}
      break;
    case RES_PROCEDIMIENTO:
      nodo = crear_procedimiento();
                                     {if (true) return nodo;}
      break;
    case RES_FUNCION:
      nodo = crear_funcion();
                                     {if (true) return nodo;}
      break;
    case RES_USUARIO:
      nodo = crear_usuario();
                                     {if (true) return nodo;}
      break;
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser crear_base() throws ParseException {
 NodoParser nodo = new NodoParser("CREAR","",0,0); Token t,id;
    t = jj_consume_token(RES_BD);
                                     nodo.hijos().add(new NodoParser("BD",t.image,t.beginLine,t.beginColumn));
    id = jj_consume_token(ID);
                                     nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
    jj_consume_token(99);
                                     {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser crear_tabla() throws ParseException {
 NodoParser nodo = new NodoParser("CREAR","",0,0); NodoParser lista; Token t,id;
    t = jj_consume_token(RES_TABLA);
                                     nodo.hijos().add(new NodoParser("TABLA",t.image,t.beginLine,t.beginColumn));
    id = jj_consume_token(ID);
                                     nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
    jj_consume_token(100);
    lista = lista_campos();
                                     nodo.hijos().add(lista);
    jj_consume_token(101);
    jj_consume_token(99);
                                     {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser campo() throws ParseException {
 NodoParser nodo = new NodoParser("CAMPO","",0,0); NodoParser tip,coms,com; Token id;
    tip = tipo();
                                     nodo.hijos().add(tip);
    id = jj_consume_token(ID);
                                     nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
         coms = new NodoParser("COMPLEMENTOS","",0,0);
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case RES_NO:
      case RES_NULO:
      case RES_AUTOINC:
      case RES_PRIMARIA:
      case RES_FORANEA:
      case RES_UNICO:
        ;
        break;
      default:
        jj_la1[29] = jj_gen;
        break label_7;
      }
      com = complemento();
                                     coms.hijos().add(com);
    }
         nodo.hijos().add(coms);
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser lista_campos() throws ParseException {
 NodoParser nodo,c;
    c = campo();
                                     nodo = new NodoParser("CAMPOS","",0,0); nodo.hijos().add(c);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 102:
        ;
        break;
      default:
        jj_la1[30] = jj_gen;
        break label_8;
      }
      jj_consume_token(102);
      c = campo();
                                     nodo.hijos().add(c);
    }
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser complemento() throws ParseException {
 NodoParser nodo = new NodoParser("COMPLEMENTO","",0,0); Token t,id;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RES_NO:
      t = jj_consume_token(RES_NO);
      jj_consume_token(RES_NULO);
                                     nodo.hijos().add(new NodoParser("NO NULO","",t.beginLine,t.beginColumn)); {if (true) return nodo;}
      break;
    case RES_NULO:
      t = jj_consume_token(RES_NULO);
                                     nodo.hijos().add(new NodoParser("NULO","",t.beginLine,t.beginColumn)); {if (true) return nodo;}
      break;
    case RES_AUTOINC:
      t = jj_consume_token(RES_AUTOINC);
                                     nodo.hijos().add(new NodoParser("AUTOINC","",t.beginLine,t.beginColumn)); {if (true) return nodo;}
      break;
    case RES_PRIMARIA:
      t = jj_consume_token(RES_PRIMARIA);
                                     nodo.hijos().add(new NodoParser("PRIMARIA","",t.beginLine,t.beginColumn)); {if (true) return nodo;}
      break;
    case RES_FORANEA:
      t = jj_consume_token(RES_FORANEA);
                                     nodo.hijos().add(new NodoParser("FORANEA","",t.beginLine,t.beginColumn));
      id = jj_consume_token(ID);
                                     nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn)); {if (true) return nodo;}
      break;
    case RES_UNICO:
      t = jj_consume_token(RES_UNICO);
                                     nodo.hijos().add(new NodoParser("UNICO","",t.beginLine,t.beginColumn)); {if (true) return nodo;}
      break;
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser crear_objeto() throws ParseException {
 NodoParser nodo = new NodoParser("CREAR","",0,0); NodoParser lista; Token t,id;
    t = jj_consume_token(RES_OBJETO);
                                     nodo.hijos().add(new NodoParser("OBJETO",t.image,t.beginLine,t.beginColumn));
    id = jj_consume_token(ID);
                                     nodo.hijos().add(new NodoParser("ID",t.image,id.beginLine,id.beginColumn));
    jj_consume_token(100);
    lista = lista_atributos();
                                     nodo.hijos().add(lista);
    jj_consume_token(101);
    jj_consume_token(99);
                                     {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser atributo() throws ParseException {
 NodoParser nodo = new NodoParser("ATRIBUTO","",0,0); NodoParser t; Token id;
    t = tipo();
                                     nodo.hijos().add(t);
    id = jj_consume_token(ID);
                                     nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn)); {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser lista_atributos() throws ParseException {
 NodoParser nodo,atr;
    atr = atributo();
                                     nodo = new NodoParser("ATRIBUTOS","",0,0); nodo.hijos().add(atr);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 102:
        ;
        break;
      default:
        jj_la1[32] = jj_gen;
        break label_9;
      }
      jj_consume_token(102);
      atr = atributo();
                                     nodo.hijos().add(atr);
    }
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser crear_procedimiento() throws ParseException {
 NodoParser nodo = new NodoParser("CREAR","",0,0); NodoParser params,sens; Token t,id,abre,cierra;
    t = jj_consume_token(RES_PROCEDIMIENTO);
                                             nodo.hijos().add(new NodoParser("PROCEDIMIENTO",t.image,t.beginLine,t.beginColumn));
    id = jj_consume_token(ID);
                                             nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
    jj_consume_token(100);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RES_DOBLE:
    case RES_ENTERO:
    case RES_CADENA:
    case RES_BOOLEAN:
    case RES_DATE:
    case RES_DATETIME:
    case ID:
      params = lista_parametros();
                                             nodo.hijos().add(params);
      break;
    default:
      jj_la1[33] = jj_gen;
      ;
    }
    jj_consume_token(101);
    abre = jj_consume_token(ABRE);
    sens = lista_sentencias();
                                             nodo.hijos().add(sens);
    cierra = jj_consume_token(CIERRA);
         nodo.inicio = abre.endLine; nodo.fin = cierra.beginLine; {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser parametro() throws ParseException {
 NodoParser nodo = new NodoParser("PARAMETRO","",0,0); NodoParser t; Token v;
    t = tipo();
                         nodo.hijos().add(t);
    v = jj_consume_token(VAR);
                         System.out.println(v.image); nodo.hijos().add(new NodoParser("VAR",v.image,v.beginLine,v.beginColumn));
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser crear_funcion() throws ParseException {
 NodoParser nodo = new NodoParser("CREAR","",0,0); NodoParser params,sens,ti; Token t,id,abre,cierra;
    t = jj_consume_token(RES_FUNCION);
                                         nodo.hijos().add(new NodoParser("FUNCION",t.image,t.beginLine,t.beginColumn));
    id = jj_consume_token(ID);
                                         nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
    jj_consume_token(100);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RES_DOBLE:
    case RES_ENTERO:
    case RES_CADENA:
    case RES_BOOLEAN:
    case RES_DATE:
    case RES_DATETIME:
    case ID:
      params = lista_parametros();
                                         nodo.hijos().add(params);
      break;
    default:
      jj_la1[34] = jj_gen;
      ;
    }
    jj_consume_token(101);
    ti = tipo();
                                         nodo.hijos().add(ti);
    abre = jj_consume_token(ABRE);
    sens = lista_sentencias();
                                         nodo.hijos().add(sens);
    cierra = jj_consume_token(CIERRA);
         nodo.inicio = abre.endLine; nodo.fin = cierra.beginLine; {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser lista_parametros() throws ParseException {
 NodoParser nodo = new NodoParser("PARAMS","",0,0); NodoParser p;
    p = parametro();
                                 nodo.hijos().add(p);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 102:
        ;
        break;
      default:
        jj_la1[35] = jj_gen;
        break label_10;
      }
      jj_consume_token(102);
      p = parametro();
                                 nodo.hijos().add(p);
    }
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser crear_usuario() throws ParseException {
 NodoParser nodo = new NodoParser("CREAR","",0,0); Token t,id,cad;
    t = jj_consume_token(RES_USUARIO);
                                 nodo.hijos().add(new NodoParser("USUARIO",t.image,t.beginLine,t.beginColumn));
    id = jj_consume_token(ID);
                                 nodo.hijos().add(new NodoParser("ID",id.image,id.beginLine,id.beginColumn));
    jj_consume_token(RES_COLOCAR);
    jj_consume_token(RES_PASSWORD);
    jj_consume_token(ASIGNA);
    cad = jj_consume_token(CADENA);
                                 nodo.hijos().add(new NodoParser("CADENA",cad.image,cad.beginLine,cad.beginColumn));
    jj_consume_token(99);
                                 {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser tipo() throws ParseException {
 Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RES_ENTERO:
      t = jj_consume_token(RES_ENTERO);
                        System.out.println("entero"); {if (true) return new NodoParser("TIPO","entero",t.beginLine,t.beginColumn);}
      break;
    case RES_CADENA:
      t = jj_consume_token(RES_CADENA);
                        System.out.println("cadena"); {if (true) return new NodoParser("TIPO","cadena",t.beginLine,t.beginColumn);}
      break;
    case RES_BOOLEAN:
      t = jj_consume_token(RES_BOOLEAN);
                         System.out.println("cadena"); {if (true) return new NodoParser("TIPO","boolean",t.beginLine,t.beginColumn);}
      break;
    case RES_DOBLE:
      t = jj_consume_token(RES_DOBLE);
                       System.out.println("caracter"); {if (true) return new NodoParser("TIPO","doble",t.beginLine,t.beginColumn);}
      break;
    case RES_DATE:
      t = jj_consume_token(RES_DATE);
                      System.out.println("fecha"); {if (true) return new NodoParser("TIPO","fecha",t.beginLine,t.beginColumn);}
      break;
    case RES_DATETIME:
      t = jj_consume_token(RES_DATETIME);
                          System.out.println("fecha y hora"); {if (true) return new NodoParser("TIPO","fechahora",t.beginLine,t.beginColumn);}
      break;
    case ID:
      t = jj_consume_token(ID);
                System.out.println("id: "+t.image); {if (true) return new NodoParser("ID",t.image,t.beginLine,t.beginColumn);}
      break;
    default:
      jj_la1[36] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

//EXP
  final public NodoParser expresion() throws ParseException {
 NodoParser nodo,ope,exp;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ENTERO:
    case DOBLE:
    case CADENA:
    case FECHA:
    case HORA:
    case VERDADERO:
    case FALSO:
    case ID:
    case VAR:
    case 100:
      ope = operacion1();

      exp = expresion2();
                             if(exp!=null){exp.hijos().addFirst(ope); {if (true) return exp;}}else{{if (true) return ope;}}
      break;
    case RES_CONTAR:
      exp = contar();
                             {if (true) return exp;}
      break;
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser lista_expresiones() throws ParseException {
 NodoParser nodo,exp;
    exp = expresion();
                                      nodo = new NodoParser("EXPRESIONES","",0,0); nodo.hijos().add(exp);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 102:
        ;
        break;
      default:
        jj_la1[38] = jj_gen;
        break label_11;
      }
      jj_consume_token(102);
      exp = expresion();
                                      nodo.hijos().add(exp);
    }
         {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser expresion2() throws ParseException {
 NodoParser nodo,ope,exp; Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MAS:
      t = jj_consume_token(MAS);
                                   nodo = new NodoParser("EXP","",t.beginLine,t.beginColumn); nodo.hijos().add(new NodoParser("OPEARIT","+",t.beginLine,t.beginColumn));
      ope = operacion1();

      exp = expresion2();
                             if(exp!=null){exp.hijos().addFirst(ope); nodo.hijos().add(exp);}else{nodo.hijos().add(ope);} {if (true) return nodo;}
      break;
    case MENOS:
      t = jj_consume_token(MENOS);
                                     nodo = new NodoParser("EXP","",t.beginLine,t.beginColumn); nodo.hijos().add(new NodoParser("OPEARIT","-",t.beginLine,t.beginColumn));
      ope = operacion1();

      exp = expresion2();
                             if(exp!=null){exp.hijos().addFirst(ope); nodo.hijos().add(exp);}else{nodo.hijos().add(ope);} {if (true) return nodo;}
      break;
    default:
      jj_la1[39] = jj_gen;
      Empty();
                             {if (true) return null;}
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser operacion1() throws ParseException {
 NodoParser nodo,tip,exp;
    tip = tipoValor();

    exp = operacion2();
                             if(exp!=null){exp.hijos().addFirst(tip); {if (true) return exp;}}else{{if (true) return tip;}}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser operacion2() throws ParseException {
 NodoParser nodo,exp,ope; Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case POR:
      t = jj_consume_token(POR);
                                   nodo = new NodoParser("EXP","",t.beginLine,t.beginColumn); nodo.hijos().add(new NodoParser("OPEARIT","*",t.beginLine,t.beginColumn));
      exp = tipoValor();

      ope = operacion2();
                             if(ope!=null){ope.hijos().addFirst(exp); nodo.hijos().add(ope);}else{nodo.hijos().add(exp);} {if (true) return nodo;}
      break;
    case DIV:
      t = jj_consume_token(DIV);
                                   nodo = new NodoParser("EXP","",t.beginLine,t.beginColumn); nodo.hijos().add(new NodoParser("OPEARIT","/",t.beginLine,t.beginColumn));
      exp = tipoValor();

      ope = operacion2();
                             if(ope!=null){ope.hijos().addFirst(exp); nodo.hijos().add(ope);}else{nodo.hijos().add(exp);} {if (true) return nodo;}
      break;
    default:
      jj_la1[40] = jj_gen;
      Empty();
                             {if (true) return null;}
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser tipoValor() throws ParseException {
 NodoParser nodo = new NodoParser("EXP","",0,0); NodoParser tipo,tipoL; Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 100:
      jj_consume_token(100);
      nodo = expresion();
      jj_consume_token(101);
                             {if (true) return nodo;}
      break;
    case ENTERO:
      t = jj_consume_token(ENTERO);
                             tipo = new NodoParser("entero",t.image,t.beginLine,t.beginColumn); nodo.hijos().add(tipo); {if (true) return nodo;}
      break;
    case CADENA:
      t = jj_consume_token(CADENA);
                             tipo = new NodoParser("cadena",t.image,t.beginLine,t.beginColumn); nodo.hijos().add(tipo); {if (true) return nodo;}
      break;
    case FECHA:
      t = jj_consume_token(FECHA);
                             tipo = new NodoParser("fecha",t.image,t.beginLine,t.beginColumn); nodo.hijos().add(tipo); {if (true) return nodo;}
      break;
    case HORA:
      t = jj_consume_token(HORA);
                             tipo = new NodoParser("fechahora",t.image,t.beginLine,t.beginColumn); nodo.hijos().add(tipo); {if (true) return nodo;}
      break;
    case DOBLE:
      t = jj_consume_token(DOBLE);
                             tipo = new NodoParser("doble",t.image,t.beginLine,t.beginColumn); nodo.hijos().add(tipo); {if (true) return nodo;}
      break;
    case VERDADERO:
      t = jj_consume_token(VERDADERO);
                             tipo = new NodoParser("boolean","1",t.beginLine,t.beginColumn); nodo.hijos().add(tipo); {if (true) return nodo;}
      break;
    case FALSO:
      t = jj_consume_token(FALSO);
                             tipo = new NodoParser("boolean","0",t.beginLine,t.beginColumn); nodo.hijos().add(tipo); {if (true) return nodo;}
      break;
    case ID:
    case VAR:
      tipoL = llamada();
                             nodo.hijos().add(tipoL); {if (true) return nodo;}
      break;
    default:
      jj_la1[41] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser control() throws ParseException {
 NodoParser nodo;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SI:
      nodo = si();
                                     {if (true) return nodo;}
      break;
    case PARA:
      nodo = para();
                                     {if (true) return nodo;}
      break;
    case SELECCIONA:
      nodo = seleccion_casos();
                                     {if (true) return nodo;}
      break;
    case MIENTRAS:
      nodo = mientras();
                                     {if (true) return nodo;}
      break;
    default:
      jj_la1[42] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser si() throws ParseException {
 NodoParser nodo,con,sen; Token t;
    t = jj_consume_token(SI);
                                     nodo = new NodoParser("SI","",t.beginLine,t.beginColumn);
    jj_consume_token(100);
    con = condicion();
                                     nodo.hijos().add(con);
    jj_consume_token(101);
    jj_consume_token(ABRE);
    sen = lista_sentencias();
                                     nodo.hijos().add(sen);
    jj_consume_token(CIERRA);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SINO:
      t = jj_consume_token(SINO);
      jj_consume_token(ABRE);
      sen = lista_sentencias();
                                     nodo.hijos().add(sen);
      jj_consume_token(CIERRA);
      break;
    default:
      jj_la1[43] = jj_gen;
      ;
    }
     {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser seleccion_casos() throws ParseException {
 NodoParser nodo,exp,cas,def,sen,sns; Token t;
    t = jj_consume_token(SELECCIONA);
                                     nodo = new NodoParser("SELECCIONA","",t.beginLine,t.beginColumn);
    jj_consume_token(100);
    exp = expresion();
                                     nodo.hijos().add(exp);
    jj_consume_token(101);
    jj_consume_token(ABRE);
    cas = casos();
                                     nodo.hijos().add(cas);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DEFECTO:
      jj_consume_token(DEFECTO);
      jj_consume_token(103);
      sen = lista_sentencias();
                                     nodo.hijos().add(sen);
      break;
    default:
      jj_la1[44] = jj_gen;
      ;
    }
    jj_consume_token(CIERRA);
                                     {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser casos() throws ParseException {
 NodoParser nodo,caso,exp,sns,sen; Token t;
    t = jj_consume_token(CASO);
                                     nodo = new NodoParser("CASOS","",t.beginLine,t.beginColumn); caso = new NodoParser("CASO","",t.beginLine,t.beginColumn);
    exp = expresion();
                                     caso.hijos().add(exp);
    jj_consume_token(103);
    sen = lista_sentencias();
                                     caso.hijos().add(sen);
     nodo.hijos().add(caso);
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CASO:
        ;
        break;
      default:
        jj_la1[45] = jj_gen;
        break label_12;
      }
      t = jj_consume_token(CASO);
                                     caso = new NodoParser("CASO","",t.beginLine,t.beginColumn);
      exp = expresion();
                                     caso.hijos().add(exp);
      jj_consume_token(103);
      sen = lista_sentencias();
                                     caso.hijos().add(sen);
         nodo.hijos().add(caso);
    }
     {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser para() throws ParseException {
 NodoParser nodo,asig,con,cre,sen; Token t;
    t = jj_consume_token(PARA);
                                 nodo = new NodoParser("PARA","",t.beginLine,t.beginColumn);
    jj_consume_token(100);
    asig = declarar();
                                 nodo.hijos().add(asig);
    con = condicion();
                                 nodo.hijos().add(con);
    jj_consume_token(99);
    cre = crecimiento();
                                 nodo.hijos().add(cre);
    jj_consume_token(101);
    jj_consume_token(ABRE);
    sen = lista_sentencias();
                                 nodo.hijos().add(sen);
    jj_consume_token(CIERRA);
                                 {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser mientras() throws ParseException {
 NodoParser nodo,con,sns,sen; Token t;
    t = jj_consume_token(MIENTRAS);
                                 nodo = new NodoParser("MIENTRAS","",t.beginLine,t.beginColumn);
    jj_consume_token(100);
    con = condicion();
                                 nodo.hijos().add(con);
    jj_consume_token(101);
    jj_consume_token(ABRE);
    sen = lista_sentencias();
                                 nodo.hijos().add(sen);
    jj_consume_token(CIERRA);
                                 {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser condicion() throws ParseException {
 NodoParser nodo,ope,con;
    ope = operando1();
                         nodo = new NodoParser("EXP","",0,0); if(ope!=null){nodo.hijos().add(ope);}
    con = condicion2();
                         if(con!=null){nodo.hijos().add(con);}
     {if (true) return nodo;}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser condicion2() throws ParseException {
 NodoParser nodo,ope,con; Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OR:
      t = jj_consume_token(OR);
                                 nodo = new NodoParser("EXP","",t.beginLine,t.beginColumn); nodo.hijos().add(new NodoParser("OPELOGICA","OR",t.beginLine,t.beginColumn));
      ope = operando1();

      con = condicion2();
                                 if(con!=null){con.hijos().addFirst(ope); nodo.hijos().add(con);}else{nodo.hijos().add(ope);} {if (true) return nodo;}
      break;
    default:
      jj_la1[46] = jj_gen;
      Empty();
                                 {if (true) return null;}
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser operando1() throws ParseException {
 NodoParser tip,ope;
    tip = tipoCondicion();
    ope = operando2();
                                 if(ope!=null){ope.hijos().addFirst(tip); {if (true) return ope;}}else{{if (true) return tip;}}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser operando2() throws ParseException {
 NodoParser nodo,tip,ope; Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AND:
      t = jj_consume_token(AND);
                                     nodo = new NodoParser("EXP","",t.beginLine,t.beginColumn); nodo.hijos().add(new NodoParser("OPELOGICA","AND",t.beginLine,t.beginColumn));
      tip = tipoCondicion();

      ope = operando2();
                                 if(ope!=null){ope.hijos().addFirst(tip); nodo.hijos().add(ope);}else{nodo.hijos().add(tip);} {if (true) return nodo;}
      break;
    default:
      jj_la1[47] = jj_gen;
      Empty();
                                 {if (true) return null;}
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser tipoCondicion() throws ParseException {
 NodoParser exp,sub,nodo; boolean no = false; Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
      // condicion -> NOT subcondicion | subcondicion;
              t = jj_consume_token(NOT);
                                     System.out.println("! -> NOT"); exp = new NodoParser("EXP","",t.beginLine,t.beginColumn);
      jj_consume_token(100);
                                     System.out.println("( -> Parentesis condicion");
      sub = subcondicion();
                                     exp.hijos().addFirst(new NodoParser("NOT","!",t.beginLine,t.beginColumn)); exp.hijos().add(sub);
      jj_consume_token(101);
                                     System.out.println(") -> Parentesis condicion"); {if (true) return exp;}
      break;
    case ENTERO:
    case DOBLE:
    case CADENA:
    case FECHA:
    case HORA:
    case VERDADERO:
    case FALSO:
    case RES_CONTAR:
    case ID:
    case VAR:
    case 100:
      sub = subcondicion();
                                     System.out.println(") -> Parentesis condicion"); {if (true) return sub;}
      break;
    default:
      jj_la1[48] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser subcondicion() throws ParseException {
 NodoParser nodo,exp,opl;
    // exp -> exp Ope_Logica exp
            exp = expresion();

    opl = operacionLogica();
                                 if(opl!=null){opl.hijos().addFirst(exp); {if (true) return opl;}}else{{if (true) return exp;}}
    throw new Error("Missing return statement in function");
  }

  final public NodoParser operacionLogica() throws ParseException {
 NodoParser nodo,exp; Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IGUAL:
      t = jj_consume_token(IGUAL);
      exp = expresion();
                           nodo = new NodoParser("EXP","",t.beginLine,t.beginColumn); nodo.hijos().add(new NodoParser("OPELOGICA","==",t.beginLine,t.beginColumn)); nodo.hijos().add(exp); {if (true) return nodo;}
      break;
    case DIFERENTE:
      t = jj_consume_token(DIFERENTE);
      exp = expresion();
                           nodo = new NodoParser("EXP","",t.beginLine,t.beginColumn); nodo.hijos().add(new NodoParser("OPELOGICA","!=",t.beginLine,t.beginColumn)); nodo.hijos().add(exp); {if (true) return nodo;}
      break;
    case MENOR:
      t = jj_consume_token(MENOR);
      exp = expresion();
                           nodo = new NodoParser("EXP","",t.beginLine,t.beginColumn); nodo.hijos().add(new NodoParser("OPELOGICA","<",t.beginLine,t.beginColumn)); nodo.hijos().add(exp); {if (true) return nodo;}
      break;
    case MENOR_IGUAL:
      t = jj_consume_token(MENOR_IGUAL);
      exp = expresion();
                           nodo = new NodoParser("EXP","",t.beginLine,t.beginColumn); nodo.hijos().add(new NodoParser("OPELOGICA","<=",t.beginLine,t.beginColumn)); nodo.hijos().add(exp); {if (true) return nodo;}
      break;
    case MAYOR_IGUAL:
      t = jj_consume_token(MAYOR_IGUAL);
      exp = expresion();
                           nodo = new NodoParser("EXP","",t.beginLine,t.beginColumn); nodo.hijos().add(new NodoParser("OPELOGICA",">=",t.beginLine,t.beginColumn)); nodo.hijos().add(exp); {if (true) return nodo;}
      break;
    case MAYOR:
      t = jj_consume_token(MAYOR);
      exp = expresion();
                           nodo = new NodoParser("EXP","",t.beginLine,t.beginColumn); nodo.hijos().add(new NodoParser("OPELOGICA",">",t.beginLine,t.beginColumn)); nodo.hijos().add(exp); {if (true) return nodo;}
      break;
    default:
      jj_la1[49] = jj_gen;
      Empty();
                           {if (true) return null;}
    }
    throw new Error("Missing return statement in function");
  }

  final public NodoParser crecimiento() throws ParseException {
 NodoParser nodo,dim,exp; Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INCREMENTO:
      t = jj_consume_token(INCREMENTO);
                             nodo = new NodoParser("INCREMENTO","++",t.beginLine,t.beginColumn); {if (true) return nodo;}
      break;
    case DECREMENTO:
      t = jj_consume_token(DECREMENTO);
                             nodo = new NodoParser("DECREMENTO","--",t.beginLine,t.beginColumn); {if (true) return nodo;}
      break;
    default:
      jj_la1[50] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public SintacticoTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[51];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
      jj_la1_init_3();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x10400000,0x10400000,0x10000000,0x10000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x2f800000,0x0,0x0,0x0,0x0,0x0,0x0,0x23000000,0x0,0x0,0x2f800000,0x0,0x0,0x0,0x0,0xfc000,0xfc000,0x0,0xfc000,0x303e00,0x0,0x0,0x0,0x303e00,0x0,0x0,0x0,0x0,0x0,0x0,0x303e00,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0xb330dc63,0xb330dc63,0xa1301c60,0xa1301c60,0xc000000,0x0,0x0,0x0,0x0,0x200,0x200,0x200,0x20000,0x0,0x0,0x0,0x0,0xc0000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xc,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1000000,0x0,0x0,0x0,0x0,0xa0000000,0x40000000,0x0,0x0,0x0,0x0,0x1000000,0x0,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x8000001c,0x8000001c,0x8000001c,0x8000001c,0x0,0x200,0x200000,0x0,0x80001000,0x0,0x0,0x0,0x0,0x0,0x200,0x80000000,0x80001000,0x0,0x0,0x200,0x200,0x80000000,0x200,0x200,0x0,0x0,0x0,0x0,0x0,0xfc00000,0x0,0xfc00000,0x0,0x80000000,0x80000000,0x0,0x80000000,0x80000000,0x0,0xc00,0x3000,0x80000000,0x18,0x0,0x2,0x1,0x10000000,0x20000000,0xc0000000,0x1f8000,0x180,};
   }
   private static void jj_la1_init_3() {
      jj_la1_3 = new int[] {0x1,0x1,0x1,0x1,0x0,0x0,0x0,0x40,0x0,0x0,0x0,0x0,0x0,0x40,0x0,0x1,0x1,0x0,0x0,0x10,0x0,0x1,0x0,0x10,0x10,0x0,0x0,0x40,0x0,0x0,0x40,0x0,0x40,0x0,0x0,0x40,0x0,0x11,0x40,0x0,0x0,0x11,0x0,0x0,0x0,0x0,0x0,0x0,0x11,0x0,0x0,};
   }

  /** Constructor with InputStream. */
  public Sintactico(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Sintactico(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new SintacticoTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 51; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 51; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Sintactico(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new SintacticoTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 51; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 51; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Sintactico(SintacticoTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 51; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(SintacticoTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 51; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[104];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 51; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 104; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
