/* Generated By:JavaCC: Do not edit this line. SintacticoMetodosConstants.java */
package com.jagt.Analizadores.XML.Metodos;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SintacticoMetodosConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINEA = 7;
  /** RegularExpression Id. */
  int MULTILINEA = 8;
  /** RegularExpression Id. */
  int ENTERO = 9;
  /** RegularExpression Id. */
  int DOBLE = 10;
  /** RegularExpression Id. */
  int CADENA = 11;
  /** RegularExpression Id. */
  int FECHA = 12;
  /** RegularExpression Id. */
  int HORA = 13;
  /** RegularExpression Id. */
  int INICIO_PROC = 14;
  /** RegularExpression Id. */
  int FIN_PROC = 15;
  /** RegularExpression Id. */
  int INICIO_NOMBRE = 16;
  /** RegularExpression Id. */
  int FIN_NOMBRE = 17;
  /** RegularExpression Id. */
  int INICIO_PARAMS = 18;
  /** RegularExpression Id. */
  int FIN_PARAMS = 19;
  /** RegularExpression Id. */
  int INICIO_SRC = 20;
  /** RegularExpression Id. */
  int FIN_SRC = 21;
  /** RegularExpression Id. */
  int INICIO_RET = 22;
  /** RegularExpression Id. */
  int FIN_RET = 23;
  /** RegularExpression Id. */
  int RES_DOBLE = 24;
  /** RegularExpression Id. */
  int RES_ENTERO = 25;
  /** RegularExpression Id. */
  int RES_CADENA = 26;
  /** RegularExpression Id. */
  int RES_BOOLEAN = 27;
  /** RegularExpression Id. */
  int RES_DATE = 28;
  /** RegularExpression Id. */
  int RES_DATETIME = 29;
  /** RegularExpression Id. */
  int VERDADERO = 30;
  /** RegularExpression Id. */
  int FALSO = 31;
  /** RegularExpression Id. */
  int RES_INSERTAR = 32;
  /** RegularExpression Id. */
  int RES_EN = 33;
  /** RegularExpression Id. */
  int RES_VALORES = 34;
  /** RegularExpression Id. */
  int RES_DONDE = 35;
  /** RegularExpression Id. */
  int RES_ACTUALIZAR = 36;
  /** RegularExpression Id. */
  int RES_BORRAR = 37;
  /** RegularExpression Id. */
  int RES_SELECCIONAR = 38;
  /** RegularExpression Id. */
  int RES_DE = 39;
  /** RegularExpression Id. */
  int RES_TABLA = 40;
  /** RegularExpression Id. */
  int RES_ORDENAR = 41;
  /** RegularExpression Id. */
  int RES_ASC = 42;
  /** RegularExpression Id. */
  int RES_DESC = 43;
  /** RegularExpression Id. */
  int RES_DECLARAR = 44;
  /** RegularExpression Id. */
  int RES_IMPRIMIR = 45;
  /** RegularExpression Id. */
  int RES_FECHA = 46;
  /** RegularExpression Id. */
  int RES_FECHAHORA = 47;
  /** RegularExpression Id. */
  int RES_CONTAR = 48;
  /** RegularExpression Id. */
  int SI = 49;
  /** RegularExpression Id. */
  int SINO = 50;
  /** RegularExpression Id. */
  int SELECCIONA = 51;
  /** RegularExpression Id. */
  int CASO = 52;
  /** RegularExpression Id. */
  int DEFECTO = 53;
  /** RegularExpression Id. */
  int DETENER = 54;
  /** RegularExpression Id. */
  int PARA = 55;
  /** RegularExpression Id. */
  int MIENTRAS = 56;
  /** RegularExpression Id. */
  int RETORNAR = 57;
  /** RegularExpression Id. */
  int INCREMENTO = 58;
  /** RegularExpression Id. */
  int DECREMENTO = 59;
  /** RegularExpression Id. */
  int PUNTO = 60;
  /** RegularExpression Id. */
  int MAS = 61;
  /** RegularExpression Id. */
  int MENOS = 62;
  /** RegularExpression Id. */
  int POR = 63;
  /** RegularExpression Id. */
  int DIV = 64;
  /** RegularExpression Id. */
  int POT = 65;
  /** RegularExpression Id. */
  int MAYOR = 66;
  /** RegularExpression Id. */
  int MENOR = 67;
  /** RegularExpression Id. */
  int IGUAL = 68;
  /** RegularExpression Id. */
  int DIFERENTE = 69;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 70;
  /** RegularExpression Id. */
  int MAYOR_IGUAL = 71;
  /** RegularExpression Id. */
  int ASIGNA = 72;
  /** RegularExpression Id. */
  int RES_NO = 73;
  /** RegularExpression Id. */
  int RES_NULO = 74;
  /** RegularExpression Id. */
  int RES_AUTOINC = 75;
  /** RegularExpression Id. */
  int RES_PRIMARIA = 76;
  /** RegularExpression Id. */
  int RES_FORANEA = 77;
  /** RegularExpression Id. */
  int RES_UNICO = 78;
  /** RegularExpression Id. */
  int OR = 79;
  /** RegularExpression Id. */
  int AND = 80;
  /** RegularExpression Id. */
  int NOT = 81;
  /** RegularExpression Id. */
  int ID = 82;
  /** RegularExpression Id. */
  int VAR = 83;
  /** RegularExpression Id. */
  int DIGITO = 84;
  /** RegularExpression Id. */
  int LETRA = 85;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\b\"",
    "<LINEA>",
    "<MULTILINEA>",
    "<ENTERO>",
    "<DOBLE>",
    "<CADENA>",
    "<FECHA>",
    "<HORA>",
    "\"<Proc>\"",
    "\"</Proc>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<params>\"",
    "\"</params>\"",
    "\"<src>\"",
    "\"</src>\"",
    "\"<ret>\"",
    "\"</ret>\"",
    "\"Double\"",
    "<RES_ENTERO>",
    "\"Text\"",
    "\"Bool\"",
    "\"Date\"",
    "\"Datetime\"",
    "<VERDADERO>",
    "<FALSO>",
    "\"Insertar\"",
    "\"En\"",
    "\"Valores\"",
    "\"Donde\"",
    "\"Actualizar\"",
    "\"Borrar\"",
    "\"Seleccionar\"",
    "\"De\"",
    "\"Tabla\"",
    "\"Ordenar_Por\"",
    "\"ASC\"",
    "\"DESC\"",
    "\"Declarar\"",
    "\"Imprimir\"",
    "\"Fecha\"",
    "\"Fecha_Hora\"",
    "\"Contar\"",
    "\"Si\"",
    "\"Sino\"",
    "\"Selecciona\"",
    "\"Caso\"",
    "\"Defecto\"",
    "\"Detener\"",
    "\"Para\"",
    "\"Mientras\"",
    "\"Retorno\"",
    "\"++\"",
    "\"--\"",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"No\"",
    "\"Nulo\"",
    "\"Autoincrementable\"",
    "\"Llave_Primaria\"",
    "\"Llave_Foranea\"",
    "\"Unico\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "<ID>",
    "<VAR>",
    "<DIGITO>",
    "<LETRA>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
  };

}
