/* Generated By:JavaCC: Do not edit this line. SintacticoMetodosConstants.java */
package com.jagt.Analizadores.XML.Metodos;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SintacticoMetodosConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINEA = 7;
  /** RegularExpression Id. */
  int MULTILINEA = 8;
  /** RegularExpression Id. */
  int INICIO_PROC = 9;
  /** RegularExpression Id. */
  int FIN_PROC = 10;
  /** RegularExpression Id. */
  int INICIO_NOMBRE = 11;
  /** RegularExpression Id. */
  int FIN_NOMBRE = 12;
  /** RegularExpression Id. */
  int INICIO_PARAMS = 13;
  /** RegularExpression Id. */
  int FIN_PARAMS = 14;
  /** RegularExpression Id. */
  int INICIO_SRC = 15;
  /** RegularExpression Id. */
  int FIN_SRC = 16;
  /** RegularExpression Id. */
  int INICIO_RET = 17;
  /** RegularExpression Id. */
  int FIN_RET = 18;
  /** RegularExpression Id. */
  int ENTERO = 19;
  /** RegularExpression Id. */
  int DOBLE = 20;
  /** RegularExpression Id. */
  int CADENA = 21;
  /** RegularExpression Id. */
  int FECHA = 22;
  /** RegularExpression Id. */
  int HORA = 23;
  /** RegularExpression Id. */
  int RES_DOBLE = 24;
  /** RegularExpression Id. */
  int RES_ENTERO = 25;
  /** RegularExpression Id. */
  int RES_CADENA = 26;
  /** RegularExpression Id. */
  int RES_BOOLEAN = 27;
  /** RegularExpression Id. */
  int RES_DATE = 28;
  /** RegularExpression Id. */
  int RES_DATETIME = 29;
  /** RegularExpression Id. */
  int VERDADERO = 30;
  /** RegularExpression Id. */
  int FALSO = 31;
  /** RegularExpression Id. */
  int RES_CREAR = 32;
  /** RegularExpression Id. */
  int RES_BD = 33;
  /** RegularExpression Id. */
  int RES_TABLA = 34;
  /** RegularExpression Id. */
  int RES_OBJETO = 35;
  /** RegularExpression Id. */
  int RES_PROCEDIMIENTO = 36;
  /** RegularExpression Id. */
  int RES_FUNCION = 37;
  /** RegularExpression Id. */
  int RETORNAR = 38;
  /** RegularExpression Id. */
  int RES_USUARIO = 39;
  /** RegularExpression Id. */
  int RES_PASSWORD = 40;
  /** RegularExpression Id. */
  int RES_COLOCAR = 41;
  /** RegularExpression Id. */
  int RES_USAR = 42;
  /** RegularExpression Id. */
  int RES_ALTERAR = 43;
  /** RegularExpression Id. */
  int RES_AGREGAR = 44;
  /** RegularExpression Id. */
  int RES_QUITAR = 45;
  /** RegularExpression Id. */
  int RES_CAMBIAR = 46;
  /** RegularExpression Id. */
  int RES_ELIMINAR = 47;
  /** RegularExpression Id. */
  int RES_INSERTAR = 48;
  /** RegularExpression Id. */
  int RES_EN = 49;
  /** RegularExpression Id. */
  int RES_VALORES = 50;
  /** RegularExpression Id. */
  int RES_DONDE = 51;
  /** RegularExpression Id. */
  int RES_ACTUALIZAR = 52;
  /** RegularExpression Id. */
  int RES_BORRAR = 53;
  /** RegularExpression Id. */
  int RES_SELECCIONAR = 54;
  /** RegularExpression Id. */
  int RES_DE = 55;
  /** RegularExpression Id. */
  int RES_OTORGAR = 56;
  /** RegularExpression Id. */
  int RES_DENEGAR = 57;
  /** RegularExpression Id. */
  int RES_PERMISOS = 58;
  /** RegularExpression Id. */
  int RES_ORDENAR = 59;
  /** RegularExpression Id. */
  int RES_ASC = 60;
  /** RegularExpression Id. */
  int RES_DESC = 61;
  /** RegularExpression Id. */
  int RES_DECLARAR = 62;
  /** RegularExpression Id. */
  int RES_IMPRIMIR = 63;
  /** RegularExpression Id. */
  int RES_FECHA = 64;
  /** RegularExpression Id. */
  int RES_FECHAHORA = 65;
  /** RegularExpression Id. */
  int RES_CONTAR = 66;
  /** RegularExpression Id. */
  int RES_BACKUP = 67;
  /** RegularExpression Id. */
  int RES_USQLDUMP = 68;
  /** RegularExpression Id. */
  int RES_COMPLETO = 69;
  /** RegularExpression Id. */
  int RES_RESTAURAR = 70;
  /** RegularExpression Id. */
  int SI = 71;
  /** RegularExpression Id. */
  int SINO = 72;
  /** RegularExpression Id. */
  int SELECCIONA = 73;
  /** RegularExpression Id. */
  int CASO = 74;
  /** RegularExpression Id. */
  int DEFECTO = 75;
  /** RegularExpression Id. */
  int DETENER = 76;
  /** RegularExpression Id. */
  int PARA = 77;
  /** RegularExpression Id. */
  int MIENTRAS = 78;
  /** RegularExpression Id. */
  int ABRE = 79;
  /** RegularExpression Id. */
  int CIERRA = 80;
  /** RegularExpression Id. */
  int INCREMENTO = 81;
  /** RegularExpression Id. */
  int DECREMENTO = 82;
  /** RegularExpression Id. */
  int PUNTO = 83;
  /** RegularExpression Id. */
  int MAS = 84;
  /** RegularExpression Id. */
  int MENOS = 85;
  /** RegularExpression Id. */
  int POR = 86;
  /** RegularExpression Id. */
  int DIV = 87;
  /** RegularExpression Id. */
  int POT = 88;
  /** RegularExpression Id. */
  int MAYOR = 89;
  /** RegularExpression Id. */
  int MENOR = 90;
  /** RegularExpression Id. */
  int IGUAL = 91;
  /** RegularExpression Id. */
  int DIFERENTE = 92;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 93;
  /** RegularExpression Id. */
  int MAYOR_IGUAL = 94;
  /** RegularExpression Id. */
  int ASIGNA = 95;
  /** RegularExpression Id. */
  int RES_NO = 96;
  /** RegularExpression Id. */
  int RES_NULO = 97;
  /** RegularExpression Id. */
  int RES_AUTOINC = 98;
  /** RegularExpression Id. */
  int RES_PRIMARIA = 99;
  /** RegularExpression Id. */
  int RES_FORANEA = 100;
  /** RegularExpression Id. */
  int RES_UNICO = 101;
  /** RegularExpression Id. */
  int OR = 102;
  /** RegularExpression Id. */
  int AND = 103;
  /** RegularExpression Id. */
  int NOT = 104;
  /** RegularExpression Id. */
  int ID = 105;
  /** RegularExpression Id. */
  int VAR = 106;
  /** RegularExpression Id. */
  int DIGITO = 107;
  /** RegularExpression Id. */
  int LETRA = 108;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\b\"",
    "<LINEA>",
    "<MULTILINEA>",
    "\"<Proc>\"",
    "\"</Proc>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<params>\"",
    "\"</params>\"",
    "\"<src>\"",
    "\"</src>\"",
    "\"<ret>\"",
    "\"</ret>\"",
    "<ENTERO>",
    "<DOBLE>",
    "<CADENA>",
    "<FECHA>",
    "<HORA>",
    "\"Double\"",
    "\"Integer\"",
    "\"Text\"",
    "\"Bool\"",
    "\"Date\"",
    "\"Datetime\"",
    "<VERDADERO>",
    "<FALSO>",
    "\"Crear\"",
    "\"Base_Datos\"",
    "\"Tabla\"",
    "\"Objeto\"",
    "\"Procedimiento\"",
    "\"Funcion\"",
    "\"Retorno\"",
    "\"Usuario\"",
    "\"Password\"",
    "\"Colocar\"",
    "\"Usar\"",
    "\"Alterar\"",
    "\"Agregar\"",
    "\"Quitar\"",
    "\"Cambiar\"",
    "\"Eliminar\"",
    "\"Insertar\"",
    "\"En\"",
    "\"Valores\"",
    "\"Donde\"",
    "\"Actualizar\"",
    "\"Borrar\"",
    "\"Seleccionar\"",
    "\"De\"",
    "\"Otorgar\"",
    "\"Denegar\"",
    "\"Permisos\"",
    "\"Ordenar_Por\"",
    "\"ASC\"",
    "\"DESC\"",
    "\"Declarar\"",
    "\"Imprimir\"",
    "\"Fecha\"",
    "\"Fecha_Hora\"",
    "\"Contar\"",
    "\"Backup\"",
    "\"USQLDUMP\"",
    "\"Completo\"",
    "\"Restaurar\"",
    "\"Si\"",
    "\"Sino\"",
    "\"Selecciona\"",
    "\"Caso\"",
    "\"Defecto\"",
    "\"Detener\"",
    "\"Para\"",
    "\"Mientras\"",
    "\"{\"",
    "\"}\"",
    "\"++\"",
    "\"--\"",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"No\"",
    "\"Nulo\"",
    "\"Autoincrementable\"",
    "\"Llave_Primaria\"",
    "\"Llave_Foranea\"",
    "\"Unico\"",
    "<OR>",
    "<AND>",
    "<NOT>",
    "<ID>",
    "<VAR>",
    "<DIGITO>",
    "<LETRA>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"\\\'\"",
    "\":\"",
  };

}
