/* Generated By:JavaCC: Do not edit this line. SintacticoPaquetesConstants.java */
package com.jagt.Analizadores.Paquetes;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SintacticoPaquetesConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LOGIN = 7;
  /** RegularExpression Id. */
  int USUARIO = 8;
  /** RegularExpression Id. */
  int BGCOLOR = 9;
  /** RegularExpression Id. */
  int PASSWORD = 10;
  /** RegularExpression Id. */
  int FIN = 11;
  /** RegularExpression Id. */
  int USQL = 12;
  /** RegularExpression Id. */
  int INSTRUCCION = 13;
  /** RegularExpression Id. */
  int PAQUETE = 14;
  /** RegularExpression Id. */
  int REPORTE = 15;
  /** RegularExpression Id. */
  int ARBOL = 16;
  /** RegularExpression Id. */
  int ENTERO = 17;
  /** RegularExpression Id. */
  int DOBLE = 18;
  /** RegularExpression Id. */
  int FECHA = 19;
  /** RegularExpression Id. */
  int HORA = 20;
  /** RegularExpression Id. */
  int VERDADERO = 21;
  /** RegularExpression Id. */
  int FALSO = 22;
  /** RegularExpression Id. */
  int RES_TABLA = 23;
  /** RegularExpression Id. */
  int RES_DONDE = 24;
  /** RegularExpression Id. */
  int RES_SELECCIONAR = 25;
  /** RegularExpression Id. */
  int RES_DE = 26;
  /** RegularExpression Id. */
  int RES_ORDENAR = 27;
  /** RegularExpression Id. */
  int RES_ASC = 28;
  /** RegularExpression Id. */
  int RES_DESC = 29;
  /** RegularExpression Id. */
  int PUNTO = 30;
  /** RegularExpression Id. */
  int MAS = 31;
  /** RegularExpression Id. */
  int MENOS = 32;
  /** RegularExpression Id. */
  int POR = 33;
  /** RegularExpression Id. */
  int DIV = 34;
  /** RegularExpression Id. */
  int POT = 35;
  /** RegularExpression Id. */
  int MAYOR = 36;
  /** RegularExpression Id. */
  int MENOR = 37;
  /** RegularExpression Id. */
  int IGUAL = 38;
  /** RegularExpression Id. */
  int DIFERENTE = 39;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 40;
  /** RegularExpression Id. */
  int MAYOR_IGUAL = 41;
  /** RegularExpression Id. */
  int OR = 42;
  /** RegularExpression Id. */
  int AND = 43;
  /** RegularExpression Id. */
  int NOT = 44;
  /** RegularExpression Id. */
  int INSTRUCCIONES = 45;
  /** RegularExpression Id. */
  int ID = 46;
  /** RegularExpression Id. */
  int VAR = 47;
  /** RegularExpression Id. */
  int DIGITO = 48;
  /** RegularExpression Id. */
  int LETRA = 49;
  /** RegularExpression Id. */
  int CADENA = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\b\"",
    "\"\\\'login\\\'\"",
    "\"\\\'usuario\\\'\"",
    "\"Bgcolor\"",
    "\"\\\'password\\\'\"",
    "\"\\\'fin\\\'\"",
    "\"\\\'usql\\\'\"",
    "\"\\\'instruccion\\\'\"",
    "\"\\\'paquete\\\'\"",
    "\"\\\'reporte\\\'\"",
    "\"\\\'arbol\\\'\"",
    "<ENTERO>",
    "<DOBLE>",
    "<FECHA>",
    "<HORA>",
    "<VERDADERO>",
    "<FALSO>",
    "\"Tabla\"",
    "\"Donde\"",
    "\"Seleccionar\"",
    "\"De\"",
    "\"Ordenar_Por\"",
    "\"ASC\"",
    "\"DESC\"",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "<OR>",
    "<AND>",
    "<NOT>",
    "<INSTRUCCIONES>",
    "<ID>",
    "<VAR>",
    "<DIGITO>",
    "<LETRA>",
    "<CADENA>",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\",\"",
    "\"<html>\"",
    "\"<head>\"",
    "\"</head>\"",
    "\"</html>\"",
    "\"<body\"",
    "\"=\"",
    "\"</body>\"",
    "\"<div>\"",
    "\"</div>\"",
    "\"<h\"",
    "\"</h\"",
    "\"<usql>\"",
    "\"</usql>\"",
    "\"(\"",
    "\")\"",
  };

}
