/* Generated By:JavaCC: Do not edit this line. SintacticoTablas.java */
package com.jagt.Analizadores.XML.Tablas;
import com.jagt.AST.*;
import com.jagt.Logica.*;

import java.util.LinkedList;

public class SintacticoTablas implements SintacticoTablasConstants {

        public static void main(String args[]) throws ParseException{

                SintacticoTablas parser = new SintacticoTablas(System.in);
                parser.inicio();

        }

  final public LinkedList<Tabla> inicio() throws ParseException {
 LinkedList<Tabla> tablas = new LinkedList<Tabla>(); Tabla t;
    jj_consume_token(INICIO_PROC);
    jj_consume_token(INICIO_RUTA);
    jj_consume_token(CADENA);
    jj_consume_token(FIN_RUTA);
    jj_consume_token(FIN_PROC);
    jj_consume_token(INICIO_OBJ);
    jj_consume_token(INICIO_RUTA);
    jj_consume_token(CADENA);
    jj_consume_token(FIN_RUTA);
    jj_consume_token(FIN_OBJ);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INICIO_TABLA:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      t = tabla();
                             tablas.add(t);
    }
    jj_consume_token(0);
         {if (true) return tablas;}
    throw new Error("Missing return statement in function");
  }

  final public Tabla tabla() throws ParseException {
 Tabla t; Token id,ruta; LinkedList<Campo> campos; Campo campo;
    jj_consume_token(INICIO_TABLA);
    jj_consume_token(INICIO_NOMBRE);
    id = jj_consume_token(ID);
    jj_consume_token(FIN_NOMBRE);
    jj_consume_token(INICIO_RUTA);
    ruta = jj_consume_token(CADENA);
                                   t = new Tabla(id.image,ruta.image.replaceAll("\u005c"",""));
    jj_consume_token(FIN_RUTA);
    jj_consume_token(INICIO_ROWS);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INICIO_CAMPO:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      campo = cuerpo();
                                 t.agregarCampo(campo);
    }
    jj_consume_token(FIN_ROWS);
    jj_consume_token(FIN_TABLA);
         {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  final public Campo cuerpo() throws ParseException {
 Campo c; int val; Token t,f; boolean n,a,p,u;
    jj_consume_token(INICIO_CAMPO);
    jj_consume_token(RES_NULO);
    jj_consume_token(39);
    n = valor();
    jj_consume_token(RES_AUTO);
    jj_consume_token(39);
    a = valor();
    jj_consume_token(RES_PRIMARIA);
    jj_consume_token(39);
    p = valor();
    jj_consume_token(RES_UNICO);
    jj_consume_token(39);
    u = valor();
    jj_consume_token(40);
    jj_consume_token(41);
    val = tipo();
    jj_consume_token(40);
    t = jj_consume_token(ID);
                                 c = new Campo(t.image,val); c.setNulo(n); c.setAutoincrementable(a); c.setPrimaria(p); c.setUnica(u);
    jj_consume_token(42);
    tipo();
    jj_consume_token(40);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INICIO_FORANEA:
      jj_consume_token(INICIO_FORANEA);
      f = jj_consume_token(ID);
                                 c.setForanea(f.image);
      jj_consume_token(FIN_FORANEA);
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    jj_consume_token(FIN_CAMPO);
         {if (true) return c;}
    throw new Error("Missing return statement in function");
  }

  final public int tipo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
      jj_consume_token(INT);
                     {if (true) return SistemaBaseDatos.ENTERO;}
      break;
    case DOUBLE:
      jj_consume_token(DOUBLE);
                     {if (true) return SistemaBaseDatos.DOBLE;}
      break;
    case TEXT:
      jj_consume_token(TEXT);
                     {if (true) return SistemaBaseDatos.TEXTO;}
      break;
    case BOOL:
      jj_consume_token(BOOL);
                     {if (true) return SistemaBaseDatos.BOOL;}
      break;
    case DATE:
      jj_consume_token(DATE);
                     {if (true) return SistemaBaseDatos.DATE;}
      break;
    case DATETIME:
      jj_consume_token(DATETIME);
                     {if (true) return SistemaBaseDatos.DATETIME;}
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public boolean valor() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RES_TRUE:
      jj_consume_token(RES_TRUE);
                     {if (true) return true;}
      break;
    case RES_FALSE:
      jj_consume_token(RES_FALSE);
                     {if (true) return false;}
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public SintacticoTablasTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[5];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x2000,0x20000,0x2000000,0xe0000000,0x18000000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x7,0x0,};
   }

  /** Constructor with InputStream. */
  public SintacticoTablas(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public SintacticoTablas(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new SintacticoTablasTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public SintacticoTablas(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new SintacticoTablasTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public SintacticoTablas(SintacticoTablasTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(SintacticoTablasTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[43];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 5; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 43; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
