/* Generated By:JavaCC: Do not edit this line. SintacticoTablasConstants.java */
package com.jagt.Analizadores.XML.Tablas;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SintacticoTablasConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIO_PROC = 7;
  /** RegularExpression Id. */
  int FIN_PROC = 8;
  /** RegularExpression Id. */
  int INICIO_OBJ = 9;
  /** RegularExpression Id. */
  int FIN_OBJ = 10;
  /** RegularExpression Id. */
  int INICIO_RUTA = 11;
  /** RegularExpression Id. */
  int FIN_RUTA = 12;
  /** RegularExpression Id. */
  int INICIO_TABLA = 13;
  /** RegularExpression Id. */
  int FIN_TABLA = 14;
  /** RegularExpression Id. */
  int INICIO_ROWS = 15;
  /** RegularExpression Id. */
  int FIN_ROWS = 16;
  /** RegularExpression Id. */
  int INICIO_CAMPO = 17;
  /** RegularExpression Id. */
  int FIN_CAMPO = 18;
  /** RegularExpression Id. */
  int INICIO_NOMBRE = 19;
  /** RegularExpression Id. */
  int FIN_NOMBRE = 20;
  /** RegularExpression Id. */
  int RES_NULO = 21;
  /** RegularExpression Id. */
  int RES_AUTO = 22;
  /** RegularExpression Id. */
  int RES_PRIMARIA = 23;
  /** RegularExpression Id. */
  int RES_UNICO = 24;
  /** RegularExpression Id. */
  int INICIO_FORANEA = 25;
  /** RegularExpression Id. */
  int FIN_FORANEA = 26;
  /** RegularExpression Id. */
  int RES_TRUE = 27;
  /** RegularExpression Id. */
  int RES_FALSE = 28;
  /** RegularExpression Id. */
  int INT = 29;
  /** RegularExpression Id. */
  int BOOL = 30;
  /** RegularExpression Id. */
  int DOUBLE = 31;
  /** RegularExpression Id. */
  int DATE = 32;
  /** RegularExpression Id. */
  int DATETIME = 33;
  /** RegularExpression Id. */
  int TEXT = 34;
  /** RegularExpression Id. */
  int CADENA = 35;
  /** RegularExpression Id. */
  int ID = 36;
  /** RegularExpression Id. */
  int DIGITO = 37;
  /** RegularExpression Id. */
  int LETRA = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\b\"",
    "\"<Procedure>\"",
    "\"</Procedure>\"",
    "\"<Object>\"",
    "\"</Object>\"",
    "\"<path>\"",
    "\"</path>\"",
    "\"<Tabla>\"",
    "\"</Tabla>\"",
    "\"<rows>\"",
    "\"</rows>\"",
    "\"<campo\"",
    "\"</campo>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"nulo\"",
    "\"auto\"",
    "\"primaria\"",
    "\"unico\"",
    "\"<foranea>\"",
    "\"</foranea>\"",
    "\"\\\"true\\\"\"",
    "\"\\\"false\\\"\"",
    "\"int\"",
    "\"bool\"",
    "\"double\"",
    "\"date\"",
    "\"datetime\"",
    "\"text\"",
    "<CADENA>",
    "<ID>",
    "<DIGITO>",
    "<LETRA>",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"</\"",
  };

}
