/* Generated By:JavaCC: Do not edit this line. SintacticoRegistrosConstants.java */
package com.jagt.Analizadores.XML.Registros;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SintacticoRegistrosConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIO_ROW = 7;
  /** RegularExpression Id. */
  int FIN_ROW = 8;
  /** RegularExpression Id. */
  int INICIO_CAMPO = 9;
  /** RegularExpression Id. */
  int FIN_CAMPO = 10;
  /** RegularExpression Id. */
  int FALSO = 11;
  /** RegularExpression Id. */
  int VERDADERO = 12;
  /** RegularExpression Id. */
  int ENTERO = 13;
  /** RegularExpression Id. */
  int DOBLE = 14;
  /** RegularExpression Id. */
  int CADENA = 15;
  /** RegularExpression Id. */
  int FECHA = 16;
  /** RegularExpression Id. */
  int HORA = 17;
  /** RegularExpression Id. */
  int ID = 18;
  /** RegularExpression Id. */
  int DIGITO = 19;
  /** RegularExpression Id. */
  int LETRA = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\b\"",
    "\"<Row>\"",
    "\"</Row>\"",
    "<INICIO_CAMPO>",
    "<FIN_CAMPO>",
    "<FALSO>",
    "<VERDADERO>",
    "<ENTERO>",
    "<DOBLE>",
    "<CADENA>",
    "<FECHA>",
    "<HORA>",
    "<ID>",
    "<DIGITO>",
    "<LETRA>",
  };

}
