/* Generated By:JavaCC: Do not edit this line. SintacticoObjetos.java */
package com.jagt.Analizadores.XML.Objetos;
import com.jagt.AST.*;
import com.jagt.Logica.*;

import java.util.LinkedList;

public class SintacticoObjetos implements SintacticoObjetosConstants {

        public int contador = 1;

        public static void main(String args[]) throws ParseException{

                SintacticoObjetos parser = new SintacticoObjetos(System.in);
                parser.inicio();

        }

  final public LinkedList<Objeto> inicio() throws ParseException {
 LinkedList<Objeto> plantillas = new LinkedList<Objeto>(); Objeto obj;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INICIO_OBJ:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      obj = objeto();
                             plantillas.add(obj);
    }
    jj_consume_token(0);
         {if (true) return plantillas;}
    throw new Error("Missing return statement in function");
  }

  final public Objeto objeto() throws ParseException {
 Objeto nuevo,c; Token t;
    jj_consume_token(INICIO_OBJ);
    jj_consume_token(INICIO_NOMBRE);
    t = jj_consume_token(ID);
                             nuevo = new Objeto(t.image,SistemaBaseDatos.OBJETO);
    jj_consume_token(FIN_NOMBRE);
    jj_consume_token(INICIO_ATR);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 22:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      c = atributo();
                            nuevo.agregarAtributo(c);
    }
    jj_consume_token(FIN_ATR);
    jj_consume_token(FIN_OBJ);
         {if (true) return nuevo;}
    throw new Error("Missing return statement in function");
  }

  final public Objeto atributo() throws ParseException {
 Objeto atr; int val; Token t;
    jj_consume_token(22);
    val = tipo();
    jj_consume_token(23);
    t = jj_consume_token(ID);
                         atr = new Objeto(t.image,val);
    jj_consume_token(24);
    tipo();
    jj_consume_token(23);
         {if (true) return atr;}
    throw new Error("Missing return statement in function");
  }

  final public int tipo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
      jj_consume_token(INT);
                     {if (true) return SistemaBaseDatos.ENTERO;}
      break;
    case DOUBLE:
      jj_consume_token(DOUBLE);
                     {if (true) return SistemaBaseDatos.DOBLE;}
      break;
    case TEXT:
      jj_consume_token(TEXT);
                     {if (true) return SistemaBaseDatos.TEXTO;}
      break;
    case BOOL:
      jj_consume_token(BOOL);
                     {if (true) return SistemaBaseDatos.BOOL;}
      break;
    case DATE:
      jj_consume_token(DATE);
                     {if (true) return SistemaBaseDatos.DATE;}
      break;
    case DATETIME:
      jj_consume_token(DATETIME);
                     {if (true) return SistemaBaseDatos.DATETIME;}
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public SintacticoObjetosTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[3];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x80,0x400000,0x7e000,};
   }

  /** Constructor with InputStream. */
  public SintacticoObjetos(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public SintacticoObjetos(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new SintacticoObjetosTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public SintacticoObjetos(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new SintacticoObjetosTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public SintacticoObjetos(SintacticoObjetosTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(SintacticoObjetosTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[25];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 3; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 25; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
