/* Generated By:JavaCC: Do not edit this line. SintacticoObjetosConstants.java */
package com.jagt.Analizadores.XML.Objetos;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SintacticoObjetosConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIO_OBJ = 7;
  /** RegularExpression Id. */
  int FIN_OBJ = 8;
  /** RegularExpression Id. */
  int INICIO_NOMBRE = 9;
  /** RegularExpression Id. */
  int FIN_NOMBRE = 10;
  /** RegularExpression Id. */
  int INICIO_ATR = 11;
  /** RegularExpression Id. */
  int FIN_ATR = 12;
  /** RegularExpression Id. */
  int INT = 13;
  /** RegularExpression Id. */
  int BOOL = 14;
  /** RegularExpression Id. */
  int DOUBLE = 15;
  /** RegularExpression Id. */
  int DATE = 16;
  /** RegularExpression Id. */
  int DATETIME = 17;
  /** RegularExpression Id. */
  int TEXT = 18;
  /** RegularExpression Id. */
  int ID = 19;
  /** RegularExpression Id. */
  int DIGITO = 20;
  /** RegularExpression Id. */
  int LETRA = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\b\"",
    "\"<Obj>\"",
    "\"</Obj>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<attr>\"",
    "\"</attr>\"",
    "\"int\"",
    "\"bool\"",
    "\"double\"",
    "\"date\"",
    "\"datetime\"",
    "\"text\"",
    "<ID>",
    "<DIGITO>",
    "<LETRA>",
    "\"<\"",
    "\">\"",
    "\"</\"",
  };

}
