/* Generated By:JavaCC: Do not edit this line. SintacticoMasterConstants.java */
package com.jagt.Analizadores.XML.Usuarios;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SintacticoMasterConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CADENA = 7;
  /** RegularExpression Id. */
  int INICIO_USUARIO = 8;
  /** RegularExpression Id. */
  int FIN_USUARIO = 9;
  /** RegularExpression Id. */
  int INICIO_NOMBRE = 10;
  /** RegularExpression Id. */
  int FIN_NOMBRE = 11;
  /** RegularExpression Id. */
  int INICIO_PASS = 12;
  /** RegularExpression Id. */
  int FIN_PASS = 13;
  /** RegularExpression Id. */
  int INICIO_PERMISOS = 14;
  /** RegularExpression Id. */
  int FIN_PERMISOS = 15;
  /** RegularExpression Id. */
  int RES_ID = 16;
  /** RegularExpression Id. */
  int ID = 17;
  /** RegularExpression Id. */
  int NUMERO = 18;
  /** RegularExpression Id. */
  int DIGITO = 19;
  /** RegularExpression Id. */
  int LETRA = 20;
  /** RegularExpression Id. */
  int FIN = 21;
  /** RegularExpression Id. */
  int IGUAL = 22;
  /** RegularExpression Id. */
  int TODOS = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\b\"",
    "<CADENA>",
    "\"<usuario\"",
    "\"</usuario>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<password>\"",
    "\"</password>\"",
    "\"<permisos>\"",
    "\"</permisos>\"",
    "\"id\"",
    "<ID>",
    "<NUMERO>",
    "<DIGITO>",
    "<LETRA>",
    "\">\"",
    "\"=\"",
    "<TODOS>",
  };

}
